@startuml Patron_Adapteur
skinparam backgroundcolor transparent
skinparam Monochrome reverse

class Client
interface Cible {
	+ requete()
}
Client -[dotted]-> Cible
class Adaptateur implements Cible {
	+ requete()
}

class Adapté {
	+ Methode()
}

Adaptateur --> "adapté" Adapté

@enduml